# Generated by Django 4.0.2 on 2022-02-09 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('menu', '0002_alter_menu_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('especification', models.CharField(max_length=250)),
                ('order_date', models.DateField(default='2022-02-09')),
                ('menu_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuoptions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
