# Generated by Django 4.0.2 on 2022-02-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuuser',
            name='order_date',
            field=models.DateField(default='2022-02-11'),
        ),
    ]
