# Generated by Django 4.0.2 on 2022-02-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_user', '0002_alter_menuuser_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuuser',
            old_name='especification',
            new_name='specification',
        ),
    ]
