# Generated by Django 4.0.2 on 2022-02-09 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b5e52d08-897b-11ec-a0ff-705681b4b5a7')),
        ),
    ]
