# Generated by Django 4.0.2 on 2022-02-11 04:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c830a91c-8af5-11ec-9602-705681b4b5a7')),
        ),
    ]
