# Generated by Django 4.0.2 on 2022-02-11 08:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('80b08212-8b11-11ec-a14e-705681b4b5a7')),
        ),
    ]
