# Generated by Django 4.0.2 on 2022-02-11 18:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menu_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6027ae68-8b6a-11ec-81e6-705681b4b5a7')),
        ),
    ]
