# Generated by Django 4.0.2 on 2022-02-11 21:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_menu_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3507dd10-8b7f-11ec-9f66-705681b4b5a7')),
        ),
    ]
