# Generated by Django 4.0.2 on 2022-02-11 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_menu_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('04f9d4ec-8b80-11ec-9aed-705681b4b5a7')),
        ),
    ]
