# Generated by Django 4.0.2 on 2022-02-11 21:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_menu_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5cbe2958-8b80-11ec-b7a2-705681b4b5a7')),
        ),
    ]
