# Generated by Django 4.0.2 on 2022-02-11 21:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_menu_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c062847a-8b82-11ec-9273-705681b4b5a7')),
        ),
    ]
