# Generated by Django 4.0.2 on 2022-02-11 21:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_alter_menu_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('01b0cba2-8b84-11ec-b9b4-705681b4b5a7')),
        ),
    ]
